# Generated by Django 3.1.6 on 2021-02-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210228_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='picture',
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='news',
            name='picture',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
