# Generated by Django 3.1.6 on 2021-03-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210315_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.TextField(default=None, max_length=500),
        ),
    ]
