# Generated by Django 3.1.6 on 2021-03-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210317_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.TextField(default=None, max_length=500, null=True),
        ),
    ]
