# Generated by Django 3.1.6 on 2021-03-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210317_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='message',
            name='isOwner',
            field=models.BooleanField(default=False),
        ),
    ]
