# Generated by Django 3.1.6 on 2021-04-09 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210319_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='raiting',
        ),
        migrations.RemoveField(
            model_name='food',
            name='raiting',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='raiting',
        ),
        migrations.RemoveField(
            model_name='place_to_go',
            name='raiting',
        ),
        migrations.AddField(
            model_name='air_ticket',
            name='air_company',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='text',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='food',
            name='text',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='hotel',
            name='text',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.person')),
                ('id_place_to_go', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.place_to_go')),
            ],
        ),
    ]
